# Generated by Django 2.1.7 on 2019-03-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_privilege',
            field=models.IntegerField(choices=[(0, 'Guests'), (10, 'Shifters'), (20, 'Shift Leaders'), (30, 'Experts'), (50, 'Administrators')], default=0),
        ),
    ]
