# Generated by Django 4.0.6 on 2022-08-26 10:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryInfo',
            fields=[
                ('runs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='Unique summary for list of runs', primary_key=True, serialize=False, size=None)),
                ('links_prompt_feedback', models.TextField(help_text='tinyurl links to plots on cmsweb.cern.ch')),
                ('special_comment', models.TextField(help_text='Special comment by shifter for this summary')),
            ],
        ),
    ]
