# Generated by Django 4.0.6 on 2022-08-26 15:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifications', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='Unique summary for list of certifications. Each element is the PK of a TrackerCertification instance', size=None, unique=True)),
                ('links_prompt_feedback', models.TextField(help_text='tinyurl links to plots on cmsweb.cern.ch')),
                ('special_comment', models.TextField(blank=True, help_text='Special comment by shifter for this summary')),
            ],
        ),
    ]
