# Generated by Django 2.1.7 on 2019-10-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openruns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openruns',
            name='state_express',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('SIGNOFF', 'SignOff')], default='OPEN', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openruns',
            name='state_prompt',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('SIGNOFF', 'SignOff')], default='OPEN', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openruns',
            name='state_rereco',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('SIGNOFF', 'SignOff')], default='OPEN', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openruns',
            name='state_rereco_ul',
            field=models.CharField(choices=[('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('SIGNOFF', 'SignOff')], default='OPEN', max_length=9),
            preserve_default=False,
        ),
    ]
