# Generated by Django 2.1.7 on 2019-10-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openruns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openruns',
            name='date_retieved',
            field=models.DateField(default='2019-10-03'),
            preserve_default=False,
        ),
    ]
