# Generated by Django 2.1.7 on 2019-10-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openruns', '0002_openruns_date_retieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openruns',
            old_name='date_retieved',
            new_name='date_retrieved',
        ),
    ]
