# Generated by Django 2.1.7 on 2019-10-09 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openruns', '0004_openruns_dataset_rereco_ul'),
    ]

    operations = [
        migrations.AddField(
            model_name='openruns',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openruns',
            name='run_number',
            field=models.PositiveIntegerField(help_text='Run number', verbose_name='Run'),
        ),
        migrations.AlterUniqueTogether(
            name='openruns',
            unique_together={('run_number', 'user')},
        ),
    ]
