# Generated by Django 4.0.4 on 2022-05-28 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotescripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptargumentbase',
            name='help_text',
            field=models.CharField(blank=True, default='', help_text='Help related to this argument', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scriptconfigurationbase',
            name='help_text',
            field=models.TextField(blank=True, default='', help_text='Help text/instructions for users', max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='scriptoutputfile',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Output file description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scriptoutputfile',
            name='filename_regex',
            field=models.CharField(help_text='Regex to use in directory to find the file', max_length=100, validators=[django.core.validators.RegexValidator]),
        ),
        migrations.AlterField(
            model_name='scriptoutputfile',
            name='mother_script',
            field=models.ForeignKey(help_text='Script instance this file is generated from', on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='remotescripts.scriptconfigurationbase'),
        ),
    ]
