# Generated by Django 4.0.4 on 2022-07-13 17:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotescripts', '0003_alter_scriptconfigurationbase_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptconfigurationbase',
            name='help_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', help_text='Help text/instructions for users', max_length=1000, null=True),
        ),
    ]
