# Generated by Django 4.0.4 on 2022-07-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotescripts', '0004_alter_scriptconfigurationbase_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptargumentbase',
            name='valid_choices',
            field=models.CharField(blank=True, default='', help_text="A comma separated list of values that the argument will be limited to (Only valid if Type is 'Choices')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scriptargumentbase',
            name='type',
            field=models.CharField(choices=[('INT', 'Integer'), ('STR', 'String'), ('CHO', 'Choices')], default='STR', max_length=3),
        ),
    ]
