# Generated by Django 4.0.6 on 2022-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotescripts', '0005_scriptargumentbase_valid_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptargumentbase',
            name='default_value',
            field=models.CharField(blank=True, help_text='Default value for this argument', max_length=50, null=True),
        ),
    ]
