# Generated by Django 4.0.6 on 2022-08-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotescripts', '0006_scriptargumentbase_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptconfigurationbase',
            name='is_running',
            field=models.BooleanField(default=False, help_text='Flag set to True while the script is executing'),
        ),
    ]
