# Generated by Django 4.0.6 on 2022-08-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotescripts', '0007_scriptconfigurationbase_is_running'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptconfigurationbase',
            options={'ordering': ['id']},
        ),
    ]
