# Generated by Django 2.1.7 on 2019-06-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsrun',
            name='hlt_physics_counter',
            field=models.BigIntegerField(help_text='HLT triggers  for Physics streams', null=True, verbose_name='HLT Triggers Physics Streams'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='l1_triggers_counter',
            field=models.BigIntegerField(help_text='Number of L1 triggers', null=True, verbose_name='L1 Triggers'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='run_type',
            field=models.CharField(choices=[('collisions', 'Collisions'), ('cosmics', 'Cosmics')], max_length=11),
        ),
    ]
