# Generated by Django 2.1.7 on 2019-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsfill',
            name='b_field',
            field=models.FloatField(help_text='Magnetic field', null=True, verbose_name='B Field'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='beta_star',
            field=models.FloatField(help_text='β*', null=True, verbose_name='β*'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='bunches_beam1',
            field=models.PositiveIntegerField(help_text='Number of bunches beam 1', null=True, verbose_name='Bunches Beam1'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='bunches_beam2',
            field=models.PositiveIntegerField(help_text='Number of bunches beam 2', null=True, verbose_name='Bunches Beam2'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='bunches_colliding',
            field=models.PositiveIntegerField(help_text='Number of colliding bunches measured by CMS', null=True, verbose_name='nCollidingBunches'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='bunches_target',
            field=models.PositiveIntegerField(help_text='Target number of colliding bunches by LHC configuration', null=True, verbose_name='nTargetBunches'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='crossing_angle',
            field=models.FloatField(help_text='Crossing angle by LHC configuration', null=True, verbose_name='Crossing Angle'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='delivered_lumi',
            field=models.FloatField(help_text='Integrated stable luminosity delivered by LHC', null=True, verbose_name='Delivered Lumi'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='downtime',
            field=models.PositiveIntegerField(help_text='Total downtime during the Fill', null=True, verbose_name='Downtime'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration of the Fill', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='efficiency_lumi',
            field=models.FloatField(help_text='The efficiency calculated by luminosity', null=True, verbose_name='Efficiency by Luminosity'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='efficiency_time',
            field=models.FloatField(help_text='The efficiency calculated by time', null=True, verbose_name='Efficiency by Time'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='energy',
            field=models.FloatField(help_text='LHC target energy', null=True, verbose_name='Energy'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='era',
            field=models.CharField(help_text='Era Name', max_length=40, null=True, verbose_name='Era'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='fill_type_party1',
            field=models.CharField(help_text='Fill Type Party 1', max_length=25, null=True, verbose_name='Fill Type Party 1'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='fill_type_party2',
            field=models.CharField(help_text='Fill Type Party 2', max_length=25, null=True, verbose_name='Fill Type Party 2'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='fill_type_runtime',
            field=models.CharField(help_text='Fill type', max_length=25, null=True, verbose_name='Fill Type'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='init_lumi',
            field=models.FloatField(help_text='Luminosity at the beginning of the fill', null=True, verbose_name='InitialLumi'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='injection_scheme',
            field=models.CharField(help_text='Injection scheme', max_length=100, null=True, verbose_name='Injection scheme'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='intensity_beam1',
            field=models.FloatField(help_text='Beam 1 peak intensity', null=True, verbose_name='IntensityBeam1'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='intensity_beam2',
            field=models.FloatField(help_text='Beam 2 peak intensity', null=True, verbose_name='IntensityBeam2'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='peak_lumi',
            field=models.FloatField(help_text='Peak of instantaneous luminosity during the fill', null=True, verbose_name='PeakLumi'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='peak_pileup',
            field=models.FloatField(help_text='Peak pileup', null=True, verbose_name='PeakPileup (interactions/BX)'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='peak_specific_lumi',
            field=models.FloatField(help_text='Peak value of average specific luminosity ', null=True, verbose_name='PeakSpecificLumi'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='recorded_lumi',
            field=models.FloatField(help_text='Integrated stable luminosity recorded by CMS', null=True, verbose_name='Recorded Lumi'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='b_field',
            field=models.FloatField(help_text='Magnetic field', null=True, verbose_name='B Field'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='clock_type',
            field=models.CharField(help_text='Clock type', max_length=4000, null=True, verbose_name='Clock type'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='cmssw_version',
            field=models.CharField(help_text='CMSSW version', max_length=4000, null=True, verbose_name='Online Version'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='components',
            field=models.CharField(help_text='List of subsystems included into the Run', max_length=1000, null=True, verbose_name='Components'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='delivered_lumi',
            field=models.FloatField(help_text='Integrated stable luminosity delivered by LHC', null=True, verbose_name='Delivered Lumi'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration of the run', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='end_lumi',
            field=models.FloatField(help_text='Luminosity at the end of the run', null=True, verbose_name='Ending Lumi'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='energy',
            field=models.PositiveIntegerField(help_text='LHC energy', null=True, verbose_name='LHC Energy'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='fill_type_party1',
            field=models.CharField(help_text='Fill Type Party 1', max_length=25, null=True, verbose_name='Fill Type Party 1'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='fill_type_party2',
            field=models.CharField(help_text='Fill Type Party 2', max_length=25, null=True, verbose_name='Fill Type Party 2'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='fill_type_runtime',
            field=models.CharField(help_text='Fill type', max_length=25, null=True, verbose_name='Fill Type'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='hlt_physics_counter',
            field=models.PositiveIntegerField(help_text='HLT triggers  for Physics streams', null=True, verbose_name='HLT Triggers Physics Streams'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='hlt_physics_rate',
            field=models.FloatField(help_text='HLT rate for Physics streams', null=True, verbose_name='HLT Rate Physics Streams'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='hlt_physics_size',
            field=models.FloatField(help_text='HLT size for Physics streams', null=True, verbose_name='HLT size Physics Streams'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='hlt_physics_throughput',
            field=models.FloatField(help_text='HLT data rate for Physics streams', null=True, verbose_name='HLT Data Rate Physics Streams'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='init_lumi',
            field=models.FloatField(help_text='Luminosity at the beginning of the run', null=True, verbose_name='Initial Lumi'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='initial_prescale_index',
            field=models.PositiveIntegerField(help_text='Initial prescale index', null=True, verbose_name='Initial Prescale Index'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='l1_hlt_mode',
            field=models.CharField(help_text='L1/HLT trigger mode', max_length=256, null=True, verbose_name='L1 HLT Mode'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='l1_hlt_mode_stripped',
            field=models.CharField(help_text='L1/HLT trigger mode', max_length=256, null=True, verbose_name='L1 HLT Mode'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='l1_key',
            field=models.CharField(help_text='L1 trigger configuration key', max_length=256, null=True, verbose_name='L1 Key'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='l1_key_stripped',
            field=models.CharField(help_text='L1 trigger configuration key', max_length=256, null=True, verbose_name='L1 Key (Stripped)'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='l1_menu',
            field=models.CharField(help_text='L1 menu name', max_length=256, null=True, verbose_name='L1 Menu'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='l1_rate',
            field=models.FloatField(help_text='L1 rate', null=True, verbose_name='L1 Rate'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='l1_triggers_counter',
            field=models.PositiveIntegerField(help_text='Number of L1 triggers', null=True, verbose_name='L1 Triggers'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='recorded_lumi',
            field=models.FloatField(help_text='Integrated stable luminosity recorded by CMS', null=True, verbose_name='Recorded Lumi'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='sequence',
            field=models.CharField(help_text='Run type', max_length=4000, null=True, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='stable_beam',
            field=models.BooleanField(help_text='Stable beam declared', null=True, verbose_name='StableBeamDeclared'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='tier0_transfer',
            field=models.BooleanField(help_text='Transfer data to tier0', null=True, verbose_name='Tier0 Transfer'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='trigger_mode',
            field=models.CharField(help_text='Running mode of CMS', max_length=256, null=True, verbose_name='TriggerMode'),
        ),
    ]
