# Generated by Django 2.1.7 on 2019-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_auto_20190620_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsrun',
            name='run_type',
            field=models.CharField(choices=[('collisions', 'Collisions'), ('cosmics', 'Cosmics')], max_length=10),
        ),
    ]
