# Generated by Django 4.0.4 on 2022-04-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0003_auto_20190624_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsfill',
            name='b_field_unit',
            field=models.CharField(default='T', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='beta_star_unit',
            field=models.CharField(default='cm', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='crossing_angle_unit',
            field=models.CharField(default='{\\mu}rad', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='delivered_lumi_unit',
            field=models.CharField(default='pb^{-1}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='energy_unit',
            field=models.CharField(default='GeV', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='init_lumi_unit',
            field=models.CharField(default='10^{34}cm^{-2}s^{-1}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='intensity_beam1_unit',
            field=models.CharField(default='10^{11}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='intensity_beam2_unit',
            field=models.CharField(default='10^{11}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='peak_lumi_unit',
            field=models.CharField(default='10^{34}cm^{-2}s^{-1}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='peak_specific_lumi_unit',
            field=models.CharField(default='10^{30}cm^{-2}s^{-1}(10^{11}p)^{-2}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='recorded_lumi_unit',
            field=models.CharField(default='pb^{-1}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='b_field_unit',
            field=models.CharField(default='T', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='delivered_lumi_unit',
            field=models.CharField(default='pb^{-1}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='end_lumi_unit',
            field=models.CharField(default='10^{34}cm^{-2}s^{-1}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='energy_unit',
            field=models.CharField(default='GeV', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='init_lumi_unit',
            field=models.CharField(default='10^{34}cm^{-2}s^{-1}', max_length=50),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='recorded_lumi_unit',
            field=models.CharField(default='pb^{-1}', max_length=50),
        ),
    ]
