# Generated by Django 4.0.4 on 2022-04-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0004_alter_omsfill_b_field_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsrun',
            name='fill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oms.omsfill'),
        ),
    ]
