# Generated by Django 4.0.4 on 2022-05-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0005_alter_omsrun_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsrun',
            name='b_field_unit',
            field=models.CharField(default='T', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='delivered_lumi_unit',
            field=models.CharField(default='pb^{-1}', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='end_lumi_unit',
            field=models.CharField(default='10^{34}cm^{-2}s^{-1}', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='energy_unit',
            field=models.CharField(default='GeV', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='hlt_key',
            field=models.CharField(help_text='HLT configuration key', max_length=256, null=True, verbose_name='HLT Key'),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='init_lumi_unit',
            field=models.CharField(default='10^{34}cm^{-2}s^{-1}', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='lumisections',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='recorded_lumi_unit',
            field=models.CharField(default='pb^{-1}', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='omsrun',
            name='run_type',
            field=models.CharField(choices=[('collisions', 'Collisions'), ('cosmics', 'Cosmics')], max_length=10, null=True),
        ),
    ]
