# Generated by Django 4.0.4 on 2022-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0007_omsrun_apv_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsfill',
            name='first_run_number',
            field=models.PositiveIntegerField(help_text='Run number for the first run in the fill', null=True, verbose_name='First run number'),
        ),
        migrations.AlterField(
            model_name='omsfill',
            name='last_run_number',
            field=models.PositiveIntegerField(help_text='Run number for the last run in the fill', null=True, verbose_name='Last run number'),
        ),
    ]
