# Generated by Django 4.0.6 on 2022-08-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0010_alter_omsrun_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omsrun',
            name='fill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oms_runs', to='oms.omsfill'),
        ),
    ]
