# Generated by Django 2.1.7 on 2019-03-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipicalComponents',
            fields=[
                ('run_number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('reconstruction', models.CharField(max_length=10)),
                ('pc1', models.FloatField()),
            ],
        ),
    ]
