# Generated by Django 2.1.7 on 2019-08-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChartData',
            new_name='ChartDataModel',
        ),
    ]
