# Generated by Django 2.1.7 on 2019-04-10 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0002_auto_20190409_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackercertification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
