# Generated by Django 2.1.7 on 2019-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0004_trackercertification_trackermap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runreconstruction',
            name='dataset',
        ),
        migrations.AddField(
            model_name='trackercertification',
            name='dataset',
            field=models.CharField(default='/test/dataset', max_length=150),
            preserve_default=False,
        ),
    ]
