# Generated by Django 2.1.7 on 2019-04-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0006_auto_20190412_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='name',
            new_name='dataset',
        ),
    ]
