# Generated by Django 2.1.7 on 2019-05-20 09:15

import certifier.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0008_auto_20190416_0857'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trackercertification',
            managers=[
                ('objects', certifier.manager.TrackerCertificationManager()),
                ('all_objects', certifier.manager.TrackerCertificationManager(alive_only=False)),
            ],
        ),
        migrations.AddField(
            model_name='trackercertification',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackercertification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackercertification',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
