# Generated by Django 2.1.7 on 2019-06-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0009_auto_20190520_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackercertification',
            name='reference_runreconstruction',
            field=models.ForeignKey(limit_choices_to={'is_reference': True}, on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='certifier.RunReconstruction'),
        ),
    ]
