# Generated by Django 2.1.7 on 2019-06-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0010_auto_20190618_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackercertification',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
