# Generated by Django 2.1.7 on 2019-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0011_auto_20190618_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackercertification',
            name='trackermap',
            field=models.CharField(choices=[('exists', 'Exists'), ('missing', 'Missing')], max_length=7),
        ),
    ]
