# Generated by Django 2.1.7 on 2019-09-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0012_auto_20190624_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
