# Generated by Django 2.1.7 on 2019-10-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0013_auto_20190930_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runreconstruction',
            name='reconstruction',
            field=models.CharField(choices=[('online', 'Online'), ('express', 'Express'), ('prompt', 'Prompt'), ('rereco', 'ReReco'), ('rerecoul', 'ReRecoUL')], max_length=8),
        ),
    ]
