# Generated by Django 4.0.4 on 2022-04-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0015_alter_trackercertification_runreconstruction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runreconstruction',
            options={'ordering': ['-run__run_number']},
        ),
    ]
