# Generated by Django 4.0.4 on 2022-05-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0016_alter_runreconstruction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackercertification',
            name='completeness_status',
            field=models.CharField(choices=[('INC', 'Incomplete'), ('COM', 'Complete')], default='INC', help_text="Certification's completeness status.", max_length=4),
        ),
    ]
