# Generated by Django 4.0.4 on 2022-05-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0018_alter_trackercertification_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackercertification',
            name='completeness_status',
        ),
        migrations.AddField(
            model_name='trackercertification',
            name='external_info_completeness',
            field=models.CharField(choices=[('INC', 'Incomplete'), ('COM', 'Complete')], default='INC', help_text='OMS/RR Information completeness status.', max_length=4),
        ),
    ]
