# Generated by Django 4.0.4 on 2022-07-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifier', '0019_remove_trackercertification_completeness_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackercertification',
            name='external_info_completeness',
        ),
        migrations.AddField(
            model_name='trackercertification',
            name='external_info_complete',
            field=models.BooleanField(default=False, help_text='OMS/RR Information completeness.'),
        ),
    ]
