# Generated by Django 4.0.6 on 2022-08-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0010_alter_omsrun_fill'),
        ('certifier', '0020_remove_trackercertification_external_info_completeness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runreconstruction',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconstruction', to='oms.omsrun'),
        ),
    ]
