# Generated by Django 4.0.6 on 2022-08-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0011_alter_omsrun_fill'),
        ('certifier', '0021_alter_runreconstruction_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runreconstruction',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconstructions', to='oms.omsrun'),
        ),
    ]
